const strings = {
    T: "T",
    HealthCare: "HealthCare",
    Home: "Home",
    FindDoc: "Find a doctor",
    Apps: "Apps",
    Testimonials: "Testimonials",
    About: "About us",
    Virtual: "Virtual healthcare for you",
    Text1: "Our service provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    Consult: "Consult today",
    Our: "Our services",
    Text2: "We provide to you the best choiches for you. Adjust it to your health needs and make sure your undergo treatment with our highly qualified doctors you can consult with us which type of service is suitable for your health",
    SearchDoctor: "Search doctor",
    SearchDoctorDescription: "Choose your doctor from thousands of specialist, general, and trusted hospitals",
    Online: "Online pharmacy",
    OnlineDescription: "Buy  your medicines with our mobile application with a simple delivery system",
    Consultation: "Consultation",
    ConsultationDescription: "Free consultation with our trusted doctors and get the best recomendations",
    Details: "Details info",
    DetailsDescription: "Free consultation with our trusted doctors and get the best recomendations",
    EmergencyCare: "Emergency care",
    EmergencyCareDescription: "You can get 24/7 urgent care for yourself or your children and your lovely family",
    Tracking: "Tracking",
    TrackingDescription: "Track and save your medical history and health data",
    LearnMore: "Learn more",
    Providers: "Leading healthcare providers",
    Text3: "We provides progressive, and affordable healthcare, accessible on mobile and online for everyone. To us, it’s not just work. We take pride in the solutions we deliver",
    DownloadMobileApps: "Download our mobile apps",
    Text4: "Our dedicated patient engagement app and web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely",
    Download: "Download",
    Review: "What our customer are saying",
    NameUser1: "Edward Newgate",
    Role: "Founder Circle",
    Review1: "“Our dedicated patient engagement app and web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely”",
    Review2: "“With just a few clicks or taps, you can securely view your medical records, test results, upcoming appointments, and medication history”",
    Review3: "“Our user-friendly interface makes it simple to navigate and find the information you need”",
    Review4: "“Plus, our app and portal are available 24/7, so you can access your health data whenever and wherever you need it. This empowers you to take a more active role in managing your health and making informed decisions about your care”",
    CheckArticle: "Check out our latest article",
    ArtickeTitle1: "Disease detection, check up in the laboratory",
    ArticleText1: "In this case, the role of the health laboratory is very important to do a disease detection...",
    ArticleTitle2: "Herbal medicines that are safe for consumption",
    ArticleText2: "Herbal medicine is very widely used at this time because of its very good for your health...",
    ArticleTitle3: "Natural care for healthy facial skin",
    ArticleText3: "A healthy lifestyle should start from now and also for your skin health. There are some...",
    ReadMore: "Read more",
    ViewAll: "View all",
    Hide: "Hide"

};

export default strings;